spring.application.name=driveaway
# Notice "driveaway" is now right before the question mark in the URI
spring.data.mongodb.uri=mongodb+srv://DriveAway_01:driveaway%401@driveaway.rm74yrq.mongodb.net/driveaway?retryWrites=true&w=majority